In [ ]:
import scqubits as scq
import qutip as qt
import numpy as np

In [5]:
two_pi = 2.0* np.pi
ten_pow_neg_3 = 1e-3

x = float(input("enter the value to be converted to rad/s"))
y = int(input("Is the value in GHz or MHz? If GHz then enter 1 , if MHz then enter 2"))
if y == 1:
    x_r = x * two_pi
    print(x,"GHz")
    print(x_r)
elif y == 2:
    print(x, "MHz")
    x_r = x * two_pi * ten_pow_neg_3
    print(x_r)
else :
    print("please enter correct values as stated")


0.4918 GHz
3.0900705340709207


In [ ]:
m = 200 # number of transmon levels
#Ej = 2.93556 #/2/pi
Ej = 18.447432061879265
#Ec = 0.73032 #/2/pi
Ec = 4.586725274241098#/2/pi
#El = 0.55097 #/2/pi
El = 5.598318108697011#/2/pi
phi_ext = 0.5 #*2*pi
flx = scq.Fluxonium(Ej,Ec,El,phi_ext,cutoff = m)

In [ ]:
def drive_amplitude_for_photon(n: int):
    '''The drive amplitudes required for the average photon number '''
    


In [6]:
x = Ej/Ec
print(x)
x = El/Ec
print(x)

4.021917808219178
1.2205479452054795


In [7]:
omega_levels = flx.eigenvals(22) - flx.eigenvals(22)[0]
print(omega_levels)

[  0.           3.54351048  18.88876687  32.16904735  48.11766148
  64.64495856  81.5155186   98.2580333  114.51369529 129.95630227
 144.36566282 157.75086907 170.4343637  182.90426322 195.52903773
 208.45337358 221.69598066 235.24294329 249.07417446 263.16601239
 277.49262464 292.02717404]


In [8]:
omega_levels = flx.eigenvals(22) - flx.eigenvals(22)[0]
print(omega_levels)

[  0.           3.54351048  18.88876687  32.16904735  48.11766148
  64.64495856  81.5155186   98.2580333  114.51369529 129.95630227
 144.36566282 157.75086907 170.4343637  182.90426322 195.52903773
 208.45337358 221.69598066 235.24294329 249.07417446 263.16601239
 277.49262464 292.02717404]


In [9]:
np.abs(omega_levels[:20])

array([  0.        ,   3.54351048,  18.88876687,  32.16904735,
        48.11766148,  64.64495856,  81.5155186 ,  98.2580333 ,
       114.51369529, 129.95630227, 144.36566282, 157.75086907,
       170.4343637 , 182.90426322, 195.52903773, 208.45337358,
       221.69598066, 235.24294329, 249.07417446, 263.16601239])

In [70]:
evals, evecs = flx.eigensys(evals_count=200)

In [57]:
evals, evecs = flx.eigensys(evals_count=22)

In [71]:
evals.shape
# (20,)

len(evecs)
# 20

200

In [72]:
N = flx.n_operator()

In [73]:
V = np.column_stack(
    [state.flatten() for state in evecs]
)

In [74]:
N_eig = V.conj().T @ N @ V

In [ ]:
[2.60485470e-32, 6.79035639e-01, 1.23816570e-15, 5.91690094e-02,
        3.85803817e-16, 2.79061907e-02, 2.54694233e-17, 7.52756648e-02,
        1.31348875e-16, 1.23023291e-02, 5.43017912e-17, 1.34367605e-02,
        6.16161634e-18, 9.36788228e-03, 7.79797079e-17, 1.99225290e-03,
        1.36156484e-17, 2.47285836e-03, 9.16886437e-17, 8.72933199e-04,
        1.11166081e-17, 7.93256132e-05]

In [ ]:
[[1.09762304e-31, 1.00692625e-01, 1.59815758e-15, 2.44904502e-01,
        2.63287583e-16, 1.58442229e-01, 1.30910961e-16, 1.67498849e-02,
        2.47125286e-16, 6.90736875e-03, 2.54633361e-17, 1.79586052e-02,
        1.97523427e-17, 6.46431682e-03, 1.25287584e-18, 1.87447037e-03,
        1.89723551e-16, 9.59249195e-04, 3.49690191e-16, 1.10218502e-04,
        7.48306213e-17, 2.24970982e-04]

In [ ]:
([[0.-1.05996211e-32j, 0.+1.14022937e-01j, 0.-1.42660548e-15j,
        0.+4.21005592e-01j, 0.+7.21443639e-16j, 0.+6.86856949e-03j,
        0.-3.60827643e-17j, 0.+2.08852006e-02j, 0.-3.58867818e-17j,
        0.+6.99144160e-03j, 0.+3.19853787e-16j, 0.-2.23613501e-03j,
        0.-2.04206139e-16j, 0.+8.73442128e-05j, 0.-1.10104782e-16j,
        0.-3.91493345e-04j, 0.+3.77264375e-18j, 0.+2.86845388e-04j,
        0.+7.68376982e-19j, 0.+1.27966853e-04j, 0.-1.47272400e-17j,
        0.-3.91414376e-05j]

In [75]:
np.abs(N_eig[:22,:22])

array([[1.09762304e-31, 1.00692625e-01, 1.59815758e-15, 2.44904502e-01,
        2.63287583e-16, 1.58442229e-01, 1.30910961e-16, 1.67498849e-02,
        2.47125286e-16, 6.90736875e-03, 2.54633361e-17, 1.79586052e-02,
        1.97523427e-17, 6.46431682e-03, 1.25287584e-18, 1.87447037e-03,
        1.89723551e-16, 9.59249195e-04, 3.49690191e-16, 1.10218502e-04,
        7.48306213e-17, 2.24970982e-04],
       [1.00692625e-01, 1.54417757e-31, 4.76802961e-01, 3.02239105e-16,
        4.67324644e-02, 1.36752647e-16, 2.22831280e-01, 1.33707165e-15,
        4.93428795e-02, 5.95219595e-16, 2.95397375e-02, 8.95132214e-16,
        2.33220982e-02, 5.39207746e-16, 8.35845657e-03, 5.22323400e-16,
        2.53303760e-03, 1.00223055e-15, 5.82396415e-03, 9.13810392e-16,
        3.29491186e-04, 1.50479574e-15],
       [1.59815758e-15, 4.76802961e-01, 4.93373860e-32, 5.96747826e-01,
        7.83719476e-16, 3.18562013e-01, 2.71196825e-16, 9.33520530e-02,
        1.50787003e-16, 2.36740980e-02, 3.63029369e-17

In [39]:
np.abs(N_eig[:25,:25])

array([[2.60485470e-32, 6.79035639e-01, 1.23816570e-15, 5.91690094e-02,
        3.85803817e-16, 2.79061907e-02, 2.54694233e-17, 7.52756648e-02,
        1.31348875e-16, 1.23023291e-02, 5.43017912e-17, 1.34367605e-02,
        6.16161634e-18, 9.36788228e-03, 7.79797079e-17, 1.99225290e-03,
        1.36156484e-17, 2.47285836e-03, 9.16886437e-17, 8.72933199e-04,
        1.11166081e-17, 7.93256132e-05],
       [6.79035639e-01, 9.30882280e-33, 3.02574263e-01, 1.42536832e-16,
        2.46508942e-01, 2.32922112e-16, 2.45518324e-01, 2.83082981e-16,
        6.91220441e-02, 3.52806941e-16, 1.88010838e-02, 1.71856534e-16,
        3.81444237e-02, 8.11816026e-17, 2.17156716e-02, 1.64230776e-17,
        6.73495150e-03, 2.16382979e-16, 3.70743404e-03, 1.96437385e-17,
        1.98196258e-03, 1.19155207e-16],
       [1.23816570e-15, 3.02574263e-01, 3.54971450e-32, 3.04515655e-01,
        8.80378712e-17, 2.19009180e-03, 7.05558929e-17, 2.47968121e-01,
        4.91444452e-16, 1.58202670e-02, 5.77101800e-17

In [42]:
N = len(evals)
print(N)
n_minus = np.zeros((N,N), dtype = complex)
for i in range(N):
    for j in range(i+1 , N):
        n_minus[i,j] = N_eig[i,j]

n_plus = n_minus.conj().T
np.allclose(N_eig, n_plus+n_minus)

22


True

In [45]:
np.abs(n_minus[:22,:22])

array([[0.00000000e+00, 6.79035639e-01, 1.23816570e-15, 5.91690094e-02,
        3.85803817e-16, 2.79061907e-02, 2.54694233e-17, 7.52756648e-02,
        1.31348875e-16, 1.23023291e-02, 5.43017912e-17, 1.34367605e-02,
        6.16161634e-18, 9.36788228e-03, 7.79797079e-17, 1.99225290e-03,
        1.36156484e-17, 2.47285836e-03, 9.16886437e-17, 8.72933199e-04,
        1.11166081e-17, 7.93256132e-05],
       [0.00000000e+00, 0.00000000e+00, 3.02574263e-01, 1.42536832e-16,
        2.46508942e-01, 2.32922112e-16, 2.45518324e-01, 2.83082981e-16,
        6.91220441e-02, 3.52806941e-16, 1.88010838e-02, 1.71856534e-16,
        3.81444237e-02, 8.11816026e-17, 2.17156716e-02, 1.64230776e-17,
        6.73495150e-03, 2.16382979e-16, 3.70743404e-03, 1.96437385e-17,
        1.98196258e-03, 1.19155207e-16],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.04515655e-01,
        8.80378712e-17, 2.19009180e-03, 7.05558929e-17, 2.47968121e-01,
        4.91444452e-16, 1.58202670e-02, 5.77101800e-17

In [17]:
import numpy as np

print(np.array(N_eig.shape))

[200 200]


In [18]:
from parameters import load_json

In [19]:
device, pulse, simulation = load_json("device_parameter.json")

print(device.n_matrix.shape)

(10, 10)


In [44]:
device, pulse, simulation = load_json("device_parameter.json")

print("Fluxonium dim:", device.fluxonium_dim)
print("n_matrix shape:", device.n_matrix.shape)
print("Resonator dim:", device.resonator_dim)

print("epsilon1:", pulse.epsilon1)
print("epsilon2:", pulse.epsilon2)



Fluxonium dim: 20
n_matrix shape: (20, 20)
Resonator dim: 65
epsilon1: 0.40840704496667307
epsilon2: 0.40840704496667307


In [21]:
import json
from dataclasses import asdict

def save_json(filename, device, pulse, simulation):
    data = {
        "device": asdict(device),
        "pulse": asdict(pulse),
        "simulation": asdict(simulation),
    }

    with open(filename, "w") as f:
        json.dump(data, f, indent=4)

In [ ]:
save_json("device_parameter.json",
          "device.nmatrix" = ,
          pulse,
          simulation
          )

In [1]:
from __future__ import annotations

import jax.numpy as jnp
import numpy as np
import dynamiqs as dq

from parameters import DeviceParameters, PulseParameters


In [4]:
def modulation(t: float, pulse: PulseParameters) -> float:
        amp = jnp.where(t< 100.0, pulse.epsilon1, jnp.where(t < 300.0, pulse.epsilon2, 0.0))
        return amp

In [8]:

for t in [0, 50, 99, 100, 150, 299, 300, 301, 500]:
    print(t, modulation(t, PulseParameters))

0 0.0
50 0.0
99 0.0
100 0.0
150 0.0
299 0.0
300 0.0
301 0.0
500 0.0


In [9]:
print(pulse.epsilon1)
print(pulse.epsilon2)
print(pulse.t_switch)
print(pulse.t_off)

NameError: name 'pulse' is not defined