In [1]:
import scqubits as scq
import qutip as qt
import numpy as np

In [87]:
m = 60 # number of transmon levels
#Ej = 2.93556 #/2/pi
Ej = 4.0
#Ec = 0.73032 #/2/pi
Ec = 1.0 #/2/pi
#El = 0.55097 #/2/pi
El = 0.75 #/2/pi
phi_ext = 0.5 #*2*pi
flx = scq.Fluxonium(Ej,Ec,El,phi_ext,cutoff = m)

In [88]:
x = Ej/Ec
print(x)
x = El/Ec
print(x)

4.0
0.75


In [106]:
omega_levels = flx.eigenvals(5) - flx.eigenvals(5)[0]
print(omega_levels)

[0.         0.38854778 3.90223828 6.11015607 9.18289193]


In [139]:
omega_levels = flx.eigenvals(20) - flx.eigenvals(20)[0]
print(omega_levels)

[ 0.          0.38854778  3.90223828  6.11015607  9.18289193 12.2289655
 15.28019802 18.13555164 20.6373502  22.70711498 24.55386541 26.49697931
 28.62129318 30.86140648 33.18640806 35.59025595 38.06348952 40.59499616
 43.17494045 45.79374894]


In [58]:
evals, evecs = flx.eigensys(evals_count=200)

In [90]:
evals, evecs = flx.eigensys(evals_count=60)

In [91]:
evals.shape
# (20,)

len(evecs)
# 20

60

In [92]:
N = flx.n_operator()

In [93]:
V = np.column_stack(
    [state.flatten() for state in evecs]
)

In [94]:
N_eig = V.conj().T @ N @ V

 /var/folders/d2/8d87_b4x1lvfx88t0zzzyhc40000gn/T/ipykernel_15132/1244231107.py: 1RuntimeWarning: overflow encountered in matmul
 /var/folders/d2/8d87_b4x1lvfx88t0zzzyhc40000gn/T/ipykernel_15132/1244231107.py: 1RuntimeWarning: invalid value encountered in matmul
 /var/folders/d2/8d87_b4x1lvfx88t0zzzyhc40000gn/T/ipykernel_15132/1244231107.py: 1

In [ ]:
np.abs(N_eig[:20,:5])

array([[1.91172162e-31, 1.58083819e-01, 2.23970222e-15, 4.74018575e-01,
        2.73469774e-16],
       [1.58083819e-01, 4.16991160e-33, 4.58182431e-01, 3.04901650e-16,
        3.84700017e-01],
       [2.23970222e-15, 4.58182431e-01, 4.19909342e-32, 7.76727626e-01,
        4.17856031e-16],
       [4.74018575e-01, 3.04901650e-16, 7.76727626e-01, 4.23032038e-33,
        5.50207210e-01],
       [2.73469774e-16, 3.84700017e-01, 4.17856031e-16, 5.50207210e-01,
        5.53279651e-32]])

In [140]:
np.abs(N_eig[:20,:20])

array([[1.91172162e-31, 1.58083819e-01, 2.23970222e-15, 4.74018575e-01,
        2.73469774e-16, 9.16785702e-02, 2.90566032e-17, 9.83185078e-02,
        1.44855939e-16, 6.17923492e-02, 4.26588476e-16, 2.57990447e-02,
        1.35111763e-17, 2.67847660e-03, 9.88637854e-17, 6.68223280e-03,
        1.22526153e-16, 3.11175444e-03, 2.00023003e-16, 2.97648939e-03],
       [1.58083819e-01, 4.16991160e-33, 4.58182431e-01, 3.04901650e-16,
        3.84700017e-01, 2.95789271e-16, 5.05716000e-02, 6.64097589e-16,
        9.98971814e-02, 6.14538710e-16, 2.87353372e-02, 4.63563057e-16,
        2.51994542e-03, 1.14521085e-15, 1.59318981e-02, 6.25729930e-16,
        7.37738379e-03, 5.48500379e-16, 5.92183031e-03, 3.16062161e-16],
       [2.23970222e-15, 4.58182431e-01, 4.19909342e-32, 7.76727626e-01,
        4.17856031e-16, 8.62787723e-02, 3.12388793e-16, 2.55045309e-01,
        2.15336043e-16, 1.21760253e-01, 9.83361920e-16, 3.67701793e-02,
        4.21955940e-16, 8.58777031e-03, 1.60981008e-16, 2.6080

In [125]:
N = len(evals)
n_minus= np.zeros((N,N), dtype = complex)
for i in range(N):
    for j in range(i+1 , N):
        n_minus[i,j] = N_eig[i,j]

n_plus = n_minus.conj().T
#print(np.abs(n_plus[:20, :20]))
print(np.abs(n_minus[:20, :20]))
np.allclose(N_eig, n_plus + n_minus)

[[0.00000000e+00 1.58083819e-01 2.23970222e-15 4.74018575e-01
  2.73469774e-16 9.16785702e-02 2.90566032e-17 9.83185078e-02
  1.44855939e-16 6.17923492e-02 4.26588476e-16 2.57990447e-02
  1.35111763e-17 2.67847660e-03 9.88637854e-17 6.68223280e-03
  1.22526153e-16 3.11175444e-03 2.00023003e-16 2.97648939e-03]
 [0.00000000e+00 0.00000000e+00 4.58182431e-01 3.04901650e-16
  3.84700017e-01 2.95789271e-16 5.05716000e-02 6.64097589e-16
  9.98971814e-02 6.14538710e-16 2.87353372e-02 4.63563057e-16
  2.51994542e-03 1.14521085e-15 1.59318981e-02 6.25729930e-16
  7.37738379e-03 5.48500379e-16 5.92183031e-03 3.16062161e-16]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.76727626e-01
  4.17856031e-16 8.62787723e-02 3.12388793e-16 2.55045309e-01
  2.15336043e-16 1.21760253e-01 9.83361920e-16 3.67701793e-02
  4.21955940e-16 8.58777031e-03 1.60981008e-16 2.60808311e-02
  1.93047169e-16 6.20099229e-03 4.14285723e-16 7.61270585e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  5.5

True

In [142]:
np.abs(n_plus[:20, :20])

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.58083819e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.23970222e-15, 4.58182431e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.0000

In [46]:
import numpy as np

print(np.array(N_eig.shape))

[40 40]


In [47]:
from parameters import load_json

In [48]:
device, pulse, simulation = load_json("device_parameter.json")

print(device.n_matrix.shape)

(20, 20)


In [23]:
device, pulse, simulation = load_json("device_parameter.json")

print("Fluxonium dim:", device.fluxonium_dim)
print("n_matrix shape:", device.n_matrix.shape)
print("Resonator dim:", device.resonator_dim)

print("epsilon1:", pulse.epsilon1)
print("epsilon2:", pulse.epsilon2)



Fluxonium dim: 20
n_matrix shape: (20, 20)
Resonator dim: 65
epsilon1: 0.251327
epsilon2: 0.204204


In [1]:
from __future__ import annotations

import jax.numpy as jnp
import numpy as np
import dynamiqs as dq

from parameters import DeviceParameters, PulseParameters


In [4]:
def modulation(t: float, pulse: PulseParameters) -> float:
        amp = jnp.where(t< 100.0, pulse.epsilon1, jnp.where(t < 300.0, pulse.epsilon2, 0.0))
        return amp

In [8]:

for t in [0, 50, 99, 100, 150, 299, 300, 301, 500]:
    print(t, modulation(t, PulseParameters))

0 0.0
50 0.0
99 0.0
100 0.0
150 0.0
299 0.0
300 0.0
301 0.0
500 0.0


In [9]:
print(pulse.epsilon1)
print(pulse.epsilon2)
print(pulse.t_switch)
print(pulse.t_off)

NameError: name 'pulse' is not defined