In [316]:
import numpy as np
import dynamiqs as dq
import qutip as qt
import matplotlib.pyplot as plt
import jax.numpy as jnp
import scipy.constants as const

In [ ]:
h_bar = const.hbar
omega_q = 6 * 1e-3
Hamiltonian = omega_q *(qt.create(20) * qt.destroy(20))
eval , evec = Hamiltonian.eigenstates()

In [448]:
def H_drive(t: float, coupling = 1e6):
    g = 0.5

    drive =  g * np.cos(omega_q * t)
    
    return drive

In [449]:
((2 * np.pi)/omega_q)

1256.6370614359173

In [450]:
t = np.arange(0, ((2 * np.pi)/omega_q), 0.01)


In [451]:
evec[0] * evec[0].dag()

Quantum object: dims=[[20], [20]], shape=(20, 20), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.

In [452]:
drive_ham = evec[0] * evec[1].dag() + evec[1] * evec[0].dag()

H_driven =  [Hamiltonian, [drive_ham, H_drive]]

In [454]:
t = np.arange(0, ((2 * np.pi)/omega_q) , 0.1)
psi_0 = qt.basis(20, 0)
e_ops = [evec[0] * evec[0].dag() ]
solver_options = { "store_states": True}
x = qt.sesolve(H_driven, psi_0, t, e_ops = e_ops, options = solver_options)

In [455]:
x.expect

[array([1.        , 0.99750208, 0.9900333 , ..., 0.9851749 , 0.99481614,
        0.99951335], shape=(12567,))]

In [456]:
def H_drive(t: float, coupling = 1e6):
    g = 0.5

    drive =  g * jnp.cos(omega_q * t)
    
    return drive

H_driven = Hamiltonian + dq.modulated( H_drive, drive_ham )

In [457]:
T = ((2 * np.pi)/omega_q)
tsave = np.linspace(0, T, 1)
floquet = dq.floquet(H_driven, T, tsave=tsave) 

|██████████| 100.0% ◆ elapsed 1.03s ◆ remaining 0.00ms     


In [458]:
floquet.quasienergies

Array([-2.4627638e-03,  2.4628877e-03,  0.0000000e+00, -4.6566129e-10,
        0.0000000e+00,  2.3283064e-10, -1.3969839e-09,  2.3283064e-10,
       -4.6566129e-10,  2.5611371e-09,  1.8626451e-09,  2.0954758e-09,
        1.8626451e-09,  2.0954758e-09,  5.8207661e-09,  1.4435500e-08,
        1.3737008e-08,  2.6309863e-08,  4.0745363e-08,  5.2386895e-08],      dtype=float32)

In [ ]:
phi = (2 * E_j/ E_c)**(0.25)()
n = 1j/np.sqrt(2)(n_zpf)(E_c / 2 *  E_j) ** (0.25)()

0.7071067811865475j

In [ ]:
qubit_hamiltonian = 4*E_c* (n**2)  + E_j * cos(phi)